# Database configuration props
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/room_rental_db?createDatabaseIfNotExist=true
    username: root
    # password: your_database_password   # Uncomment this line and replace 'your_database_password' with the actual password
    driver-class-name: com.mysql.cj.jdbc.Driver

# Hibernate props
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
